"""4 Migration

Revision ID: ed34c8ab53ad
Revises: 1e78a03778f5
Create Date: 2018-09-08 18:40:05.276160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed34c8ab53ad'
down_revision = '1e78a03778f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pitchss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitchss', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
